{{- if .Values.master.secondaryingress.enabled }}
{{- $serviceName := include "jenkins.fullname" . -}}
{{- $servicePort := .Values.master.servicePort -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: {{ .Values.master.secondaryingress.apiVersion }}
{{- end }}
kind: Ingress
metadata:
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.master.componentName }}"
    {{- if .Values.master.secondaryingress.labels -}}
    {{ toYaml .Values.master.secondaryingress.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.master.secondaryingress.annotations }}
  annotations: {{ toYaml .Values.master.secondaryingress.annotations | nindent 4 }}
  {{- end }}
  name: {{ template "jenkins.fullname" . }}-secondary
spec:
  rules:
    - host: {{ .Values.master.secondaryingress.hostName }}
      http:
        paths:
        {{- range .Values.master.secondaryingress.paths }}
          - path: {{ . | quote }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
        {{- end}}
{{- if .Values.master.secondaryingress.tls }}
  tls:
{{ toYaml .Values.master.secondaryingress.tls | indent 4 }}
{{- end -}}
{{- end }}
